#!/bin/bash

DEST="$HOME/Dropbox/Backup/Android/backup-full-$(date +%F).ab"

echo "Starting adb backup at $(date +%T)..."
./adb backup -apk -all -shared -nosystem -f "$DEST"
if [ $? -eq 0 ]
then
	echo "Backup completed at $(date +%T)."
else
	echo "Something went wrong, please check. Aborting at $(date +%T)."

	if [ -f "$DEST" ]; then
		rm "$DEST"
	fi
fi

